version: '3.5'

services:
  order-service:
    container_name: order-service-ctn
    build:
      context: ./order-service
      dockerfile: Dockerfile
    image: tramhuuducvn/order-service-img
    environment:
      - PROFILE=dev
      - DATABASE_NAME=test
      - DATABASE_URL=mongodb://<usr>:<pwd>@test-account.mongo.cosmos.azure.com:10255/?ssl=true&replicaSet=globaldb&retrywrites=false&maxIdleTimeMS=120000&appName=@test-account@
      - AZURE_SERVICEBUS_NAMESPACE_CONNECTION_STRING=Endpoint=sb://test.servicebus.windows.net/;SharedAccessKeyName=RootManageSharedAccessKey;SharedAccessKey=<key>
    ports:
      - 8080:8080
    networks:
      - order-system-network
    volumes:
      - /home/dobermann/logs/order-service/:/logs/

  inventory-service:
    container_name: inventory-service-ctn
    build:
      context: ./inventory-service
      dockerfile: Dockerfile
    image: tramhuuducvn/inventory-service-img
    environment:
      - PROFILE=dev
      - DATABASE_NAME=test
      - DATABASE_URL=mongodb://<usr>:<pwd>@test-account.mongo.cosmos.azure.com:10255/?ssl=true&replicaSet=globaldb&retrywrites=false&maxIdleTimeMS=120000&appName=@test-account@
      - AZURE_SERVICEBUS_NAMESPACE_CONNECTION_STRING=Endpoint=sb://test.servicebus.windows.net/;SharedAccessKeyName=RootManageSharedAccessKey;SharedAccessKey=<key>
      - AZURE_SERVICEBUS_NAMESPACE=ordersyssvcbusnamespace
      - AZURE_SERVICEBUS_QUEUE_NAME=inventory_queue
    ports:
      - 8081:8081
    networks:
      - order-system-network
    volumes:
      - /home/dobermann/logs/inventory-service/:/logs/

  delivery-service:
    container_name: delivery-service-ctn
    build:
      context: ./delivery-service
      dockerfile: Dockerfile
    image: tramhuuducvn/delivery-service-img
    environment:
      - PROFILE=dev
      - DATABASE_NAME=test
      - DATABASE_URL=mongodb://<usr>:<pwd>@test-account.mongo.cosmos.azure.com:10255/?ssl=true&replicaSet=globaldb&retrywrites=false&maxIdleTimeMS=120000&appName=@test-account@
      - AZURE_SERVICEBUS_NAMESPACE_CONNECTION_STRING=Endpoint=sb://test.servicebus.windows.net/;SharedAccessKeyName=RootManageSharedAccessKey;SharedAccessKey=<key>
      - AZURE_SERVICEBUS_NAMESPACE=ordersyssvcbusnamespace
      - AZURE_SERVICEBUS_QUEUE_NAME=delivery_queue
    ports:
      - 8082:8082
    networks:
      - order-system-network
    volumes:
      - /home/dobermann/logs/delivery-service/:/logs/
  
  grafana_agent:
    image: grafana/agent
    restart: always
    volumes:
      - ./grafana_agent.yml:/etc/agent-config/grafana_agent.yml
      - /home/dobermann/temp/agent:/etc/agent
      - /home/dobermann/logs/order-service/:/tmp/logs/order-service/
      - /home/dobermann/logs/delivery-service/:/tmp/logs/delivery-service/
      - /home/dobermann/logs/inventory-service/:/tmp/logs/inventory-service/
    entrypoint:
      - /bin/grafana-agent
      - -config.file=/etc/agent-config/grafana_agent.yml
      - -metrics.wal-directory=/tmp/agent/wal
      - -enable-features=integrations-next
      - -config.expand-env
      - -config.enable-read-api
    ports:
      - "3200:3200"
    network_mode: "host"
    # networks:
    #   - order-system-network

networks:
  order-system-network:
    name: order-system-network
    driver: bridge