name: "Workflow from branch"

on:
  push:
    branches:
      - "**"
  workflow_dispatch:
    inputs:
      use_environment:
        description: "Environment in which the application will be deployed."
        required: true
        type: choice
        options:
          - dev
          - qa
          - non-prod
          - prod

jobs:
  build:
    runs-on: ubuntu-latest
    environment: ${{ inputs.use_environment }}
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Export secret
        shell: bash
        run: |
          echo ENV is ${{ inputs.use_environment }}
          export USERNAME=${{secrets.USERNAME}}
          echo username is ${{secrets.USERNAME}}
          echo $USERNAME
          export AZURE_CLIENT_ID=${{secrets.AZURE_CLIENT_ID}}
          echo AZURE_CLIENT_ID is ${{secrets.AZURE_CLIENT_ID}} 
          echo $AZURE_CLIENT_ID
          export AZURE_SUBSCRIPTION_ID=${{secrets.AZURE_SUBSCRIPTION_ID}}
          echo AZURE_SUBSCRIPTION_ID is ${{secrets.AZURE_SUBSCRIPTION_ID}} 
          echo $AZURE_SUBSCRIPTION_ID
          export AZURE_SERVICEBUS_NAMESPACE_CONNECTION_STRING=${{secrets.AZURE_SERVICEBUS_NAMESPACE_CONNECTION_STRING}}
          echo AZURE_SERVICEBUS_NAMESPACE_CONNECTION_STRING is ${{secrets.AZURE_SERVICEBUS_NAMESPACE_CONNECTION_STRING}} 
          echo $AZURE_SERVICEBUS_NAMESPACE_CONNECTION_STRING
