name: "Workflow from branch"

on:
  push:
    branches:
      - "**"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Export secret
        shell: bash
        run: |
          echo AZURE_CLIENT_ID is ${{secrets.AZURE_CLIENT_ID}} 
          export AZURE_CLIENT_ID=${{secrets.AZURE_CLIENT_ID}}
          echo AZURE_SERVICEBUS_NAMESPACE_CONNECTION_STRING is ${{secrets.AZURE_SERVICEBUS_NAMESPACE_CONNECTION_STRING}} 
          export AZURE_SERVICEBUS_NAMESPACE_CONNECTION_STRING=${{secrets.AZURE_SERVICEBUS_NAMESPACE_CONNECTION_STRING}}
