name: "Build & Push image to DockerHub"

on:
  # push:
  #   branches:
  #     - "**"
  # pull_request:
  #   branches: ["main"]
  workflow_dispatch:

jobs:
  build:
    uses: ./.github/workflows/build.yml
    with:
      upload-artifact: true
  
  push:
    runs-on:  ubuntu-latest
    needs: [ build ]
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: List Item
        run: |
          cd order-service && ls && cd ../
          cd delivery-service && ls && cd ../
          cd inventory-service && ls && cd ../

      - name: Download Jar Artifact
        uses: actions/download-artifact@v3
        with:
          name: order-system

      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}

      - name: Build & Push to DockerHub
        uses: docker/build-push-action@v3
        with: 
          context: ./order-service
          push: true
          tags: tramhuuducvn/order-service-img
  
  
  
