name: "Build & Push image to DockerHub"

on:
  # push:
  #   branches:
  #     - "**"
  # pull_request:
  #   branches: ["main"]
  workflow_dispatch:

jobs:
  build:
    uses: ./.github/workflows/build.yml
    with:
      upload-artifact: true
  
  push:
    runs-on:  ubuntu-latest
    needs: [ build ]
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: List Item
        run: |
          echo order-DIR && cd order-service/target && ls && cd ../../
          echo delivery-DIR && cd delivery-service/target && ls && cd ../../
          echo inventory-DIR && cd inventory-service/target && ls && cd ../../

      - name: Download Jar Artifact
        uses: actions/download-artifact@v3
        with:
          name: order-system

      - name: List Item After Download
        run: |
          echo order-DIR && cd order-service/target && ls && cd ../../
          echo delivery-DIR && cd delivery-service/target && ls && cd ../../
          echo inventory-DIR && cd inventory-service/target && ls && cd ../../

      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}

      - name: Build & Push Order Service to DockerHub
        uses: docker/build-push-action@v3
        with: 
          context: ./order-service
          push: true
          tags: tramhuuducvn/order-service-img
      
      - name: Build & Push Inventory Service to DockerHub
        uses: docker/build-push-action@v3
        with: 
          context: ./inventory-service
          push: true
          tags: tramhuuducvn/inventory-service-img

      - name: Build & Push Delivery to DockerHub
        uses: docker/build-push-action@v3
        with: 
          context: ./delivery-service
          push: true
          tags: tramhuuducvn/delivery-service-img
  
  
  
