name: "Build & Test"

on:
  workflow_call:
    inputs:
      upload:
        required: false
        type: boolean
        default: false

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Setup JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: "17"
          distribution: "zulu"
          cache: maven

      - name: Build with Maven
        run: mvn install

      - name: Upload JAR files
        uses: actions/upload-artifact@v3
        if: ${{inputs.upload == 'true'}}
        with: 
          name: order-system
          path: |
            ./order-service/target
            ./inventory-service/target
            ./delivery-service/target
          retention-days: 3

