name: "Build & Push image to DockerHub"

on:
  # push:
  #   branches:
  #     - "**"
  # pull_request:
  #   branches: ["main"]
  workflow_dispatch:

jobs:
  build:
    uses: ./.github/workflows/build.yml
  
  push:
    runs-on:  ubuntu-latest
    steps:
      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}
      - name: Build & Push to DockerHub
        uses: docker/build-push-action@v3
        with: 
          context: ./order-service
          push: true
          tags: tramhuuducvn/order-service-img
  
  
  
