name: Trigger auto deployment for delivery-service-application

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ main ]
    paths:
    - '**'
    - '.github/workflows/delivery-service-application-AutoDeployTrigger-6da72ff8-3b74-486e-97b4-07d1147d518f.yml'

  # Allow manual trigger 
  workflow_dispatch:      

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions: 
      id-token: write #This is required for requesting the OIDC JWT Token
      contents: read #Required when GH token is used to authenticate with private repo

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Azure Login
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.DELIVERYSERVICEAPPLICATION_AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.DELIVERYSERVICEAPPLICATION_AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.DELIVERYSERVICEAPPLICATION_AZURE_SUBSCRIPTION_ID }}

      - name: Build and push container image to registry
        uses: azure/container-apps-deploy-action@v2
        with:
          appSourcePath: ${{ github.workspace }}/delivery-service
          _dockerfilePathKey_: _dockerfilePath_
          registryUrl: hub.docker.com
          registryUsername: ${{ secrets.DELIVERYSERVICEAPPLICATION_REGISTRY_USERNAME }}
          registryPassword: ${{ secrets.DELIVERYSERVICEAPPLICATION_REGISTRY_PASSWORD }}
          containerAppName: delivery-service-application
          resourceGroup: order-system
          imageToBuild: hub.docker.com/delivery-service-application:${{ github.sha }}
          _buildArgumentsKey_: |
            _buildArgumentsValues_


