name: On Push Codex

on:
  push:
    branches:
      - "**"
  # pull_request:
  #   branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        project:
          - delivery-service
          - inventory-service
          - order-service
          - payment-service

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
      - name: Setup JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: "17"
          distribution: "zulu"
          cache: maven
      - name: Build & Test
        run: |
          cd ${{ matrix.project }}
          mvn -B package --file pom.xml
